# -*- coding: utf-8 -*-
"""small_projects-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hF2O4DwAIQb5yJGxZGWdztRh1cXiz4JS

** Student Grade Analyzer**
"""

#a NumPy array of 50 randomly generated scores (0–100)
import numpy as np

scores=np.random.randint(0,101,50)
scores

mean=np.mean(scores)
mean

median=np.median(scores)
median

standard_deviation=np.std(scores)
standard_deviation

percentile=np.percentile(scores, 50)
percentile

maximum=np.max(scores)
print("Highest score is",maximum)
minimum=np.min(scores)
print("lowest score is:",minimum)

#Boolean masking
failed_students=scores<40
print("failed students are:",failed_students)
print(scores[failed_students])

distiction=scores>85
print("Distinction scores :",distiction)
print(scores[distiction]) #Boolean indexing.
print("Number of students with distinction:",np.sum(distiction))

#normalization
normalized_scores=(scores-minimum)/(maximum-minimum)
print("normalized scores :",normalized_scores)

#reshape
scores_reshaped=scores.reshape(5,10)
print("reshaped scores :",scores_reshaped)

# Commented out IPython magic to ensure Python compatibility.
# %cd ..

"""**BONUS:- CALCULATE WEIGHTAGE**"""

theory_marks=np.random.randint(0,100,size=50)
practical_marks=np.random.randint(0,51,size=50)
print("theory marks :",theory_marks)
print("practical marks :",practical_marks)

theory_weightage=0.4
practical_weightage=0.6
final_scores=(theory_weightage*theory_marks)+(practical_weightage*practical_marks)
print("final score :",final_scores)

!git clone https://github.com/bloody14/data-science.git

ls

# Commented out IPython magic to ensure Python compatibility.
# %cd data-science

# Commented out IPython magic to ensure Python compatibility.
# %%writefile student_grade_analyzer.py